- name: Install, configure, and start the service
  block:
    - name: Copy the Service script configuration file to the host
      template:
        src: templates/aa-run-before-shutdown.service.j2
        dest: /etc/systemd/system/aa-run-before-shutdown.service
        mode: "0644"

    - name: Daemon Reload
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start the service
      ansible.builtin.systemd:
        name: aa-run-before-shutdown
        state: started
        enabled: yes
  tags: service
  become: true
